services:

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: drdb
      POSTGRES_USER: druser
      POSTGRES_PASSWORD: drpass
    ports:
      - "5432:5432"
    #Postgres automatically runs any .sql scripts inside the local folder only on first initialization
    volumes: 
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  api:
    build: ../app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - db